#!/usr/bin/env bash

# From https://stackoverflow.com/a/246128/4048201
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
STATE_DIR=$CURRENT_DIR/../marketplace_state

DOCKER_CONTAINER_ID=$(docker run -tid --rm --name Marketplace -v $STATE_DIR:/data -p 8545:8545 trufflesuite/ganache-cli --db /data --debug --verbose --allowUnlimitedContractSize --mnemonic "main blouse fashion brand own rocket fluid notable vacuum gain guitar leaf" -i 666)
echo "Docker container started: $DOCKER_CONTAINER_ID"