#!/usr/bin/env bash

PARENT_DIRECTORY="${PWD%/*}" 
STATE_DIR="marketplace_state"
STATE_DIR_PATH="$PARENT_DIRECTORY/$STATE_DIR"

if [ -d "$DIR" ]; then
    echo "State directory does not exist. No need to reset state."
    exit 0
fi

cd $STATE_DIR_PATH
LAST_BLOCK_ID_LINE=$(ls -1Alt | grep -Eo "\!blocks\!([0-9]*)$" | head -n 1)
LAST_BLOCK_ID=$(echo $LAST_BLOCK_ID_LINE | grep -oE "\d+")
echo "Last block ID saved in state: $LAST_BLOCK_ID"

LAST_BLOCK_LOG_INFO_FILE="!blockLogs!length"
LAST_BLOCK_INFO_FILE="!blocks!length"

echo $LAST_BLOCK_ID > "$LAST_BLOCK_LOG_INFO_FILE"
echo $LAST_BLOCK_ID > "$LAST_BLOCK_INFO_FILE"

echo "Blockchain state reset according to block info."